# version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Note: In production,we usually do not expose port 5432 to the public internet for security
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready -U postgres -d simpledb"]
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    # image: mianahsan/taskflow-backend:latest # Pulls directly from Docker Hub!
    image: mianahsan/taskflow-backend:${APP_VERSION} # Pulls directly from Docker Hub!
    container_name: backend
    restart: always
    ports:
      - "5000:3000"
      # - "3000:3000"

    environment:
      # DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/simpledb"
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}"
    # depends_on:
    #   - postgres
    depends_on:
      postgres:
        condition: service_healthy
    # env_file:
    #   - .env

    # ======== Here we are adding health check for backend ==========
    # healthcheck:
    #   test:
    #     ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)}).on('error', () => process.exit(1))",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    # image: mianahsan/taskflow-frontend:latest # Pulls directly from Docker Hub!
    image: mianahsan/taskflow-frontend:${APP_VERSION} # Pulls directly from Docker Hub!
    container_name: frontend
    restart: always
    ports:
      - "3000:5173"
      # - "5173:5173"
    depends_on:
      - backend

    # ======= Here we are adding health check for frontend ========
    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "-q", "http://localhost:5173"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s

volumes:
  postgres-data:
