version: "3.18"

services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Note: In production, we usually DO NOT expose port 5432 to the public internet for security

  backend:
    image: mianahsan/taskflow-backend:latest # Pulls directly from Docker Hub!
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env

  frontend:
    image: mianahsan/taskflow-frontend:latest # Pulls directly from Docker Hub!
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres-data:
