name: CI (Continuous Integration) TESTING
on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  # ================= CI =================
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install Backend
        working-directory: backend
        run: npm install

      - name: Build Backend
        working-directory: backend
        run: npm run build

      - name: Install Frontend
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Build Backend Docker Image
        # run: docker build -t backend ./backend
        # run: docker build \
        #   -t ${{ secrets.DOCKER_USERNAME }}/taskflow-backend:latest \
        #   ./backend
        # run: |
        #   docker build \
        #   -t ${{ secrets.DOCKER_USERNAME }}/taskflow-backend:${{ github.ref_name }} \
        #   -t ${{ secrets.DOCKER_USERNAME }}/taskflow-backend:latest \
        #   ./backend
        run: |
          docker build \
            -t taskflow-backend:test \
            ./backend

      - name: Build Frontend Docker Image
        # run: docker build -t frontend ./frontend
        # run: docker build \
        #   -t ${{ secrets.DOCKER_USERNAME }}/taskflow-frontend:latest \
        #   ./frontend
        # run: |
        #   docker build \
        #   -t ${{ secrets.DOCKER_USERNAME }}/taskflow-frontend:${{ github.ref_name }} \
        #   -t ${{ secrets.DOCKER_USERNAME }}/taskflow-frontend:latest \
        #   ./frontend
        run: |
          docker build \
            -t taskflow-frontend:test \
            ./frontend

        # ✅ Remove Docker Hub tags from the CI build
        # The purpose of CI is only to verify that the Dockerfile builds successfully. You don't need production image names.
        # Why?
        # During a Pull Request:
        # We don't push the images.
        # We don't deploy them.
        # We only want to know: "Does the Docker build succeed?"
        # Your CI pipeline now becomes
        # Pull Request
        #       │
        #       ▼
        # Checkout Code
        #       │
        #       ▼
        # Install Backend
        #       │
        #       ▼
        # Build Backend
        #       │
        #       ▼
        # Install Frontend
        #       │
        #       ▼
        # Build Frontend
        #       │
        #       ▼
        # Build Backend Docker Image
        #       │
        #       ▼
        # Build Frontend Docker Image
        #       │
        #       ▼
        # ✅ Ready to Merge

        # No Docker Hub.
        # No SSH.
        # No production server.

        # ============== IMP STEP TO USE THIS ci.yml =============
        # so now for just build means ci what we will do we will push code to new branch and then create manuall pull request to check the successfull build
