name: CD (Continuous Deployment) || Release & Deploy PIPELINE
on:
  push:
    tags:
      - "v*"

  # pull_request:
  #   branches:
  #     - main

jobs:
  # ================= CD =================
  deploy:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Copy docker-compose.prod.yml to your Ubuntu VM
      - name: Copy docker-compose to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "~/taskflow/"

      - name: Build Backend Docker Image
        # run: docker build -t backend ./backend
        # run: docker build \
        #   -t ${{ secrets.DOCKER_USERNAME }}/taskflow-backend:latest \
        #   ./backend
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/taskflow-backend:${{ github.ref_name }} \
          -t ${{ secrets.DOCKER_USERNAME }}/taskflow-backend:latest \
          ./backend

      # - name: Build Backend
      #   run: docker build -t ${{ secrets.DOCKER_USERNAME }}/taskflow-backend ./backend

      - name: Push Backend Docker Image
        # run: docker push ${{ secrets.DOCKER_USERNAME }}/taskflow-backend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/taskflow-backend:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/taskflow-backend:latest

      # - name: Build Frontend
      #   run: docker build -t ${{ secrets.DOCKER_USERNAME }}/taskflow-frontend ./frontend

      - name: Build Frontend Docker Image
        # run: docker build -t frontend ./frontend
        # run: docker build \
        #   -t ${{ secrets.DOCKER_USERNAME }}/taskflow-frontend:latest \
        #   ./frontend
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/taskflow-frontend:${{ github.ref_name }} \
          -t ${{ secrets.DOCKER_USERNAME }}/taskflow-frontend:latest \
          ./frontend

      - name: Push Frontend Docker Image
        # run: docker push ${{ secrets.DOCKER_USERNAME }}/taskflow-frontend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/taskflow-frontend:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/taskflow-frontend:latest

      # UPDATED: Deploy with proper SSH configuration
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }} # Use the port from secrets
          # port: 2222 # Fixed port
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "✅ SSH connection successful!"
            whoami
            pwd
            ls -la

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          APP_VERSION: ${{ github.ref_name }}

        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          envs: DB_USER,DB_PASSWORD,DB_NAME,APP_VERSION

          script: |
            set -e

            cd ~/taskflow

            echo "======================================"
            echo "🚀 Starting deployment"
            echo "======================================"

            NEW_VERSION="${APP_VERSION}"

            echo "New version: ${NEW_VERSION}"

            if [ -f current_version ]; then
              PREVIOUS_VERSION=$(cat current_version)
            else
              echo "❌ current_version file does not exist!"
              exit 1
            fi

            echo "Previous version: ${PREVIOUS_VERSION}"

            ###################################################
            # Function to write .env
            ###################################################
            write_env() {
            cat > .env <<EOF
            DB_USER=${DB_USER}
            DB_PASSWORD=${DB_PASSWORD}
            DB_NAME=${DB_NAME}
            APP_VERSION=${APP_VERSION}
            EOF
            }

            ###################################################
            # Validate variables
            ###################################################

            [ -z "$DB_USER" ] && { echo "DB_USER missing"; exit 1; }
            [ -z "$DB_PASSWORD" ] && { echo "DB_PASSWORD missing"; exit 1; }
            [ -z "$DB_NAME" ] && { echo "DB_NAME missing"; exit 1; }

            ###################################################
            # DEPLOY NEW VERSION
            ###################################################

            APP_VERSION="${NEW_VERSION}"
            write_env

            echo "Deploying version:"
            cat .env

            docker compose \
              -f docker-compose.prod.yml \
              --env-file .env \
              config | grep image

            echo "📦 Pulling..."

            docker compose \
              -f docker-compose.prod.yml \
              --env-file .env \
              pull

            echo "🚀 Starting..."

            docker compose \
              -f docker-compose.prod.yml \
              --env-file .env \
              up -d --force-recreate

            docker inspect backend --format '{{.Config.Image}}'

            ###################################################
            # HEALTH CHECK
            ###################################################

            MAX_RETRIES=30
            RETRY=0

            while [ $RETRY -lt $MAX_RETRIES ]; do

              STATUS=$(docker inspect \
                  --format='{{.State.Health.Status}}' \
                  backend)

              echo "Backend status: $STATUS"

              if [ "$STATUS" = "healthy" ]; then
                  break
              fi

              if [ "$STATUS" = "unhealthy" ]; then
                  break
              fi

              RETRY=$((RETRY+1))

              sleep 5

            done

            STATUS=$(docker inspect --format='{{.State.Health.Status}}' backend)

            ###################################################
            # SUCCESS
            ###################################################

            if [ "$STATUS" = "healthy" ]; then

                echo "$NEW_VERSION" > current_version

                echo "======================================"
                echo "✅ Deployment Successful"
                echo "======================================"

                docker compose \
                  -f docker-compose.prod.yml \
                  --env-file .env \
                  ps

                exit 0
            fi

            # =================================
            # FAILED -> ROLLBACK
            # =================================

            echo "======================================"
            echo "❌ Deployment Failed"
            echo "Starting Rollback..."
            echo "======================================"

            # ✅ Download the previous version's docker-compose.prod.yml
            echo "📥 Downloading docker-compose.prod.yml from ${PREVIOUS_VERSION}..."
            if curl -o docker-compose.prod.yml \
              "https://raw.githubusercontent.com/approoffice-max/workflow/${PREVIOUS_VERSION}/docker-compose.prod.yml" 2>/dev/null; then
              echo "✅ Downloaded successfully"
            else
              echo "❌ Failed to download. Using existing file."
            fi

            # ✅ Rewrite .env with previous version
            APP_VERSION="${PREVIOUS_VERSION}"
            write_env

            echo "Rollback version:"
            cat .env

            docker compose \
              -f docker-compose.prod.yml \
              --env-file .env \
              config | grep image

            echo "📦 Pulling previous image..."

            docker compose \
              -f docker-compose.prod.yml \
              --env-file .env \
              pull

            echo "🔄 Restoring..."

            docker compose \
              -f docker-compose.prod.yml \
              --env-file .env \
              up -d --force-recreate

            docker inspect backend --format '{{.Config.Image}}'

            # echo "======================================"
            # echo "❌ Deployment Failed"
            # echo "Starting Rollback..."
            # echo "======================================"

            # # ✅ USE PREVIOUS VERSION'S DOCKER-COMPOSE FILE
            # echo "📥 Using docker-compose.prod.yml from ${PREVIOUS_VERSION}..."
            # git checkout v${PREVIOUS_VERSION} -- docker-compose.prod.yml

            # # ✅ Rewrite .env with previous version
            # APP_VERSION="${PREVIOUS_VERSION}"
            # write_env

            # echo "Rollback version:"
            # cat .env

            # docker compose \
            #   -f docker-compose.prod.yml \
            #   --env-file .env \
            #   config | grep image

            # echo "📦 Pulling previous image..."

            # docker compose \
            #   -f docker-compose.prod.yml \
            #   --env-file .env \
            #   pull

            # echo "🔄 Restoring..."

            # docker compose \
            #   -f docker-compose.prod.yml \
            #   --env-file .env \
            #   up -d --force-recreate

            # docker inspect backend --format '{{.Config.Image}}'

            # ⏳ WAIT AGAIN
            RETRY=0

            while [ $RETRY -lt $MAX_RETRIES ]; do

              STATUS=$(docker inspect \
                  --format='{{.State.Health.Status}}' \
                  backend)

              echo "Rollback status: $STATUS"

              if [ "$STATUS" = "healthy" ]; then
                  break
              fi

              RETRY=$((RETRY+1))

              sleep 5

            done

            STATUS=$(docker inspect --format='{{.State.Health.Status}}' backend)

            # ✅ SUCCESSFUL ROLLBACK
            if [ "$STATUS" = "healthy" ]; then

                echo "$PREVIOUS_VERSION" > current_version

                echo "======================================"
                echo "✅ Rollback Successful"
                echo "======================================"

                docker compose \
                  -f docker-compose.prod.yml \
                  --env-file .env \
                  ps

                exit 1  # Rollback succeeded, but deployment failed
            fi

            # ❌ ROLLBACK FAILED
            echo "======================================"
            echo "🚨 Rollback Failed"
            echo "======================================"

            echo "Container Image:"
            docker inspect backend --format '{{.Config.Image}}'

            echo "Backend Logs:"
            docker logs backend --tail 100

            echo "Health Logs:"
            docker inspect backend \
              --format '{{range .State.Health.Log}}{{println .Output}}{{end}}'

            exit 1

            # ###################################################
            # # FAILED -> ROLLBACK
            # ###################################################

            # echo "======================================"
            # echo "❌ Deployment Failed"
            # echo "Starting Rollback..."
            # echo "======================================"

            # ###################################################
            # # IMPORTANT
            # # Rewrite .env with previous version
            # ###################################################

            # APP_VERSION="${PREVIOUS_VERSION}"
            # write_env

            # echo "Rollback version:"
            # cat .env

            # docker compose \
            #   -f docker-compose.prod.yml \
            #   --env-file .env \
            #   config | grep image

            # echo "📦 Pulling previous image..."

            # docker compose \
            #   -f docker-compose.prod.yml \
            #   --env-file .env \
            #   pull

            # echo "🔄 Restoring..."

            # docker compose \
            #   -f docker-compose.prod.yml \
            #   --env-file .env \
            #   up -d --force-recreate

            # docker inspect backend --format '{{.Config.Image}}'

            # ###################################################
            # # WAIT AGAIN
            # ###################################################

            # RETRY=0

            # while [ $RETRY -lt $MAX_RETRIES ]; do

            #   STATUS=$(docker inspect \
            #       --format='{{.State.Health.Status}}' \
            #       backend)

            #   echo "Rollback status: $STATUS"

            #   if [ "$STATUS" = "healthy" ]; then
            #       break
            #   fi

            #   RETRY=$((RETRY+1))

            #   sleep 5

            # done

            # STATUS=$(docker inspect --format='{{.State.Health.Status}}' backend)

            # ###################################################
            # # SUCCESSFUL ROLLBACK
            # ###################################################

            # if [ "$STATUS" = "healthy" ]; then

            #     echo "$PREVIOUS_VERSION" > current_version

            #     echo "======================================"
            #     echo "✅ Rollback Successful"
            #     echo "======================================"

            #     docker compose \
            #       -f docker-compose.prod.yml \
            #       --env-file .env \
            #       ps

            #     exit 1
            # fi

            # ###################################################
            # # ROLLBACK FAILED
            # ###################################################

            # echo "======================================"
            # echo "🚨 Rollback Failed"
            # echo "======================================"

            # echo "Container Image:"
            # docker inspect backend --format '{{.Config.Image}}'

            # echo "Backend Logs:"
            # docker logs backend --tail 100

            # echo "Health Logs:"
            # docker inspect backend \
            #   --format '{{range .State.Health.Log}}{{println .Output}}{{end}}'

            # exit 1
